-- Tabla de Departamentos
CREATE TABLE MAE_DEPARTAMENTO (
  ID_DEPARTAMENTO INTEGER PRIMARY KEY,
  NOMBRE VARCHAR(50) NOT NULL
);

-- Tabla de Provincias
CREATE TABLE MAE_PROVINCIA (
  ID_PROVINCIA INTEGER PRIMARY KEY,
  ID_DEPARTAMENTO INTEGER NOT NULL,
  NOMBRE VARCHAR(50) NOT NULL,
  FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES MAE_DEPARTAMENTO (ID_DEPARTAMENTO)
);


-- Tabla de Distritos
CREATE TABLE MAE_DISTRITO (
  ID_DISTRITO INTEGER PRIMARY KEY,
  ID_PROVINCIA INTEGER NOT NULL,
  NOMBRE VARCHAR(50) NOT NULL,
  FOREIGN KEY (ID_PROVINCIA) REFERENCES MAE_PROVINCIA (ID_PROVINCIA)
);

-- Tabla de Direcciones
CREATE TABLE MAE_DIRECCION (
  ID_DIRECCION INTEGER PRIMARY KEY,
  ID_DISTRITO INTEGER NOT NULL,
  REFERENCIA VARCHAR(200),
  FOREIGN KEY (ID_DISTRITO) REFERENCES MAE_DISTRITO (ID_DISTRITO)
);

-- Tabla de tipos de documentos
CREATE TABLE MAE_TIPO_DOCUMENTO (
  ID_TIPO_DOCUMENTO INTEGER PRIMARY KEY,
  DESCRIPCION VARCHAR(50) NOT NULL
);

-- Tabla de unidades
CREATE TABLE MAE_UNIDADES (
  ID_UNIDAD INTEGER PRIMARY KEY,
  DESCRIPCION VARCHAR(50) NOT NULL
);

-- Tabla de proveedores
CREATE TABLE MAE_PROVEEDOR (
  ID_PROVEEDOR INTEGER PRIMARY KEY,
  ID_TIPO_DOCUMENTO INTEGER NOT NULL,  
  ID_DIRECCION INTEGER,
  DIRECCION VARCHAR(200) NOT NULL,
  NOMBRE VARCHAR(100) NOT NULL,
  TELEFONO VARCHAR(12) NOT NULL,
  CORREO VARCHAR(50),
  FOREIGN KEY (ID_TIPO_DOCUMENTO) REFERENCES MAE_TIPO_DOCUMENTO (ID_TIPO_DOCUMENTO),
  FOREIGN KEY (ID_DIRECCION) REFERENCES MAE_DIRECCION (ID_DIRECCION)
);

-- Tabla de productos
CREATE TABLE MAE_PRODUCTO (
  ID_PRODUCTO INTEGER PRIMARY KEY,
  ID_UNIDAD INTEGER NOT NULL,
  NOMBRE VARCHAR(255) NOT NULL,
  DESCRIPCION TEXT,
  PESO FLOAT NOT NULL,
  FOREIGN KEY (ID_UNIDAD) REFERENCES MAE_UNIDADES (ID_UNIDAD)
);

-- Tabla de clientes
CREATE TABLE MAE_CLIENTE (
  ID_CLIENTE INTEGER PRIMARY KEY,
  ID_TIPO_DOCUMENTO INTEGER NOT NULL,
  ID_DOCUMENTO INTEGER NOT NULL,
  ID_DIRECCION INTEGER,
  NUM_DOCUMENTO VARCHAR(50) NOT NULL,
  DIRECCION VARCHAR(200) NOT NULL,
  NOMBRE VARCHAR(100) NOT NULL,
  TELEFONO VARCHAR(12) NOT NULL,
  FOREIGN KEY (ID_TIPO_DOCUMENTO) REFERENCES MAE_TIPO_DOCUMENTO (ID_TIPO_DOCUMENTO),
  FOREIGN KEY (ID_DIRECCION) REFERENCES MAE_DIRECCION (ID_DIRECCION)
);

-- Tabla de transportistas
CREATE TABLE MAE_TRANSPORTISTA (
  ID_TRANSPORTISTA INTEGER PRIMARY KEY,
  ID_TIPO_DOCUMENTO INTEGER NOT NULL  ,
  NOMBRE VARCHAR(50) NOT NULL,
  APELLIDO VARCHAR(50) NOT NULL,
  NUM_LICENCIA VARCHAR(10) NOT NULL,
  FOREIGN KEY (ID_TIPO_DOCUMENTO) REFERENCES MAE_TIPO_DOCUMENTO (ID_TIPO_DOCUMENTO)
);

-- Tabla de vehículos
CREATE TABLE MAE_VEHICULO (
  ID_VEHICULO INTEGER PRIMARY KEY,
  PLACA VARCHAR(10) NOT NULL,
  CATEGORIA VARCHAR(10) NOT NULL,
  CAPACIDAD FLOAT NOT NULL,
  IND_RETORNO BOOLEAN NOT NULL
);

-- Tabla de cabecera de guía de remisión
CREATE TABLE TRS_CABECERA_GR (
  ID_CABECERA INTEGER PRIMARY KEY,
  ID_PROVEEDOR INTEGER NOT NULL,
  ID_CLIENTE INTEGER NOT NULL,
  ID_TRANSPORTISTA INTEGER NOT NULL,
  ID_VEHICULO INTEGER NOT NULL,
  NUM_GUIA VARCHAR(50) NOT NULL,
  FECHA_EMI DATE NOT NULL,
  HORA_EMI TIME NOT NULL,
  MOTIVO_TRAS TEXT NOT NULL,
  MODALIDAD VARCHAR(30) NOT NULL,
  FOREIGN KEY (ID_PROVEEDOR) REFERENCES MAE_PROVEEDOR (ID_PROVEEDOR),
  FOREIGN KEY (ID_CLIENTE) REFERENCES MAE_CLIENTE (ID_CLIENTE),
  FOREIGN KEY (ID_TRANSPORTISTA) REFERENCES MAE_TRANSPORTISTA (ID_TRANSPORTISTA),
  FOREIGN KEY (ID_VEHICULO) REFERENCES MAE_VEHICULO (ID_VEHICULO)
);

-- Tabla de detalle de guía de remisión
CREATE TABLE TRS_DETALLE_GR (
  ID_CABECERA INTEGER NOT NULL,
  ID_PRODUCTO INTEGER NOT NULL,
  NUM_FACTURA VARCHAR(10) NOT NULL,
  CANTIDAD_PROD INTEGER NOT NULL,
  PESO_TOTAL FLOAT NOT NULL,
  FOREIGN KEY (ID_CABECERA) REFERENCES TRS_CABECERA_GR (ID_CABECERA),
  FOREIGN KEY (ID_PRODUCTO) REFERENCES MAE_PRODUCTO (ID_PRODUCTO)
);
